[build]
  publish = "."
    functions = "netlify/functions"

    [functions]
      node_bundler = "esbuild"

      [functions."plan"]
        timeout = 26

        [functions."speak"]
          timeout = 26

          [functions."status"]
            timeout = 26
